import { useTranslation } from 'next-i18next'
import Head from 'next/head'
export default function Home() {
  const { t } = useTranslation()
  return (
    <>
      <Head>
        <title>{t('Create Next App')} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div></div>
      </main>
    </>
  )
}
